### ISSUE TITLE
obfuscate .JSON file

### ISSUE THREAD

**Issue by SiNaPsEr0x** [ClaudiuGeorgiu/Obfuscapk#158]
Can I protect the contents of JSON configuration files?

**Comment by SiNaPsEr0x** [comment]
I know otherwise I wouldn’t ask ahaha

**Comment by ClaudiuGeorgiu** [comment]
Well, the answer to your question is currently no, you can't protect the content of JSON configuration files, because there is no obfuscator implemented for your specific use case. Maybe you can use [asset encryption](https://github.com/ClaudiuGeorgiu/Obfuscapk/tree/master/src/obfuscapk/obfuscators/asset_encryption), but this could work only if your JSON files are loaded as assets. This could be however a future enhancement, but it would be helpful if you provided more details about what you are trying to achieve.

**Comment by SiNaPsEr0x** [comment]
I blurred everything with obfuscapk but precisely the json no... if we had the integral project with Android studio I could integrate allatori... do you think you can release everything as an Android studio project?

**Comment by ClaudiuGeorgiu** [comment]
> do you think you can release everything as an Android studio project?

No, sorry, I'm not even sure that's possible.
