### ISSUE TITLE
i am getting this error

### ISSUE THREAD

**Issue by NarenderModi** [ClaudiuGeorgiu/Obfuscapk#16]
usage: python3.7 -m obfuscapk.cli [-h] -o OBFUSCATOR [-w DIR]
                                  [-d OUT_APK] [-i] [-p] [-k VT_API_KEY]
                                  <APK_FILE>
python3.7 -m obfuscapk.cli: error: argument -p/--show-progress: ignored explicit argument '-w'

**Comment by ClaudiuGeorgiu** [comment]
Hi, please use the [bug report issue template](https://github.com/ClaudiuGeorgiu/Obfuscapk/blob/3adbf7bfa84adf117326409c683e375ceb5a5df4/.github/ISSUE_TEMPLATE/bug_report.md) if you want to report a bug. This issue is incomplete, how am I supposed to help if you didn't event include the command that generated the error? I guess the error is due to a missing space between the parameters `-p` and `-w`.
