### ISSUE TITLE
Use Obfusapk but i still can open with JarDx and look inside dex file

### ISSUE THREAD

**Issue by tracer8** [ClaudiuGeorgiu/Obfuscapk#36]
Hi,
I'm using Obfusapk to obfuscate my apk, but after use all of this commands:
python -m obfuscapk.cli -o LibEncryption -o ResStringEncryption -o AssetEncryption -o ConstStringEncryption -o Rebuild -o NewAlignment -o NewSignature input.apk

New APK is still open and view code like normal with JarDX tools. Is this normal?
Because i thought encryption is encrypt dex file, so nobody can normaly open it and view anycode of mine.

**Comment by ClaudiuGeorgiu** [comment]
Hi, none of the obfuscators contained in Obfuscapk will encrypt directly the dex file(s) contained in the application. You will still be able to open the application by using tools like Jadx & co., only some parts of the code could/should be harder to understand due to the obfuscation (but what exactly is obfuscated depends on the obfuscator).

**Comment by tracer8** [comment]
Oh, i got it.
I will try to use obfuscate type like rename code. It's seem easier than
Proguard, and it can ignore 3rd library to prevent error too.
