### ISSUE TITLE
Obfuscator Rename generate same name everytime

### ISSUE THREAD

**Issue by tracer8** [ClaudiuGeorgiu/Obfuscapk#41]
Hi,
After use ClassRename, i have found some bugs(maybe not):
## Steps:
- Try to Obfuscate use RenameClass
- Result 1 : p4d236d9a.pc5e83bf4
- Result 2: p4d236d9a.pc5e83bf4
- Result 3: p4d236d9a.pc5e83bf4

Class renamed always be the same as many times i try to obfuscate. If it is not a bug, how can i have different results every time?

**Comment by tracer8** [comment]
I have fix by add random key on method generate string:
```
def get_string_md5(input_string: str) -> str:
    stringToEncode = input_string + randomKeyForRename
    return md5(stringToEncode.encode()).hexdigest()
```

**Comment by ClaudiuGeorgiu** [comment]
Hi, it looks like you solved your issue. I'w writing an answer just for completeness.

> Class renamed always be the same as many times i try to obfuscate. If it is not a bug, how can i have different results every time?

This is by design, in order to have reproducible results, part of the md5 hash of the original string is used as the new name:
https://github.com/ClaudiuGeorgiu/Obfuscapk/blob/75cbc4e0c02c87aaf4797c0afbc18c21f2196457/src/obfuscapk/obfuscators/class_rename/class_rename.py#L34-L36

If you need a random string you can use:
https://github.com/ClaudiuGeorgiu/Obfuscapk/blob/75cbc4e0c02c87aaf4797c0afbc18c21f2196457/src/obfuscapk/util.py#L115-L116

And remove the fixed seed (otherwise the results won't change no matter how many times you run the tool):
https://github.com/ClaudiuGeorgiu/Obfuscapk/blob/75cbc4e0c02c87aaf4797c0afbc18c21f2196457/src/obfuscapk/util.py#L18-L19
