### ISSUE TITLE
MethodRename not working

### ISSUE THREAD

**Issue by tracer8** [ClaudiuGeorgiu/Obfuscapk#42]
## Steps:
- I use simple commands:
python -m obfuscapk.cli -o FieldRename -o MethodRename -o Rebuild -o NewAlignment -o NewSignature -i -p input.apk
- Success build and install, app running good.

## Results:
- Only Fields renamed, Methods not rename at all.
- Bellow is my screenshot from decompile tool

![PicPick_058](https://user-images.githubusercontent.com/15725821/86818956-3ccc7c80-c0b1-11ea-8bb8-e4bbe59b75e4.jpg)

**Comment by ClaudiuGeorgiu** [comment]
Hi, are those methods declared by you in the code?

**Comment by tracer8** [comment]
Yes, it is my code.

**Comment by tracer8** [comment]
I checked, it ignore my method because it is "virtual methods".
I did't understand why MethodRename ignore "virtual methods" by default? And why my simple methods on activity is mark is "virtual methods" ?
Here is my class :
```
package com.sample;

import androidx.appcompat.app.AppCompatActivity;

import android.os.Bundle;
import android.util.Log;
import android.view.View;
import android.view.ViewGroup;

import com.sample33.testing.R;

public class ActivitySampleAd extends AppCompatActivity
{
	private String admobId = "AAAAAAAAAAAAAAAAAAAAAAAAAAAA";
    private String admobVideoId = "AAAAAAAAAAAAAAAAAAAAAAAAAAAA";
    private String fanId = "AAAAAAAAAAAAAAAAAAAAAAAAAAAA";
    private String mediationTestId = "AAAAAAAAAAAAAAAAAAAAAAAAAAAA";

    private LinearLayout nativeContainer;
	
    @Override
    protected void onCreate(Bundle savedInstanceState)
    {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_sample_ad);
    }

    public void ShowInterstitial(View view)
    {
    }

    public void ShowReward(View view)
    {
       
    }

    public void ShowBannerBig(View view)
    {
    }

    @Override
    protected void onResume()
    {
        super.onResume();
    }

    @Override
    protected void onPause()
    {
        super.onPause();
    }
}

```

**Comment by tracer8** [comment]
I found out some reason can make my method is virtual:
- My method call from layout XML, here is "onClick" of button
- My method not calling on anywhere

**Comment by ClaudiuGeorgiu** [comment]
Hi, a virtual method is a method that is not private, static, or final, and is also not a constructor ([source](https://source.android.com/devices/tech/dalvik/dalvik-bytecode)). In your case the methods are virtual because they are public. As you pointed out, virtual methods are ignored by default:
https://github.com/ClaudiuGeorgiu/Obfuscapk/blob/75cbc4e0c02c87aaf4797c0afbc18c21f2196457/src/obfuscapk/obfuscators/method_rename/method_rename.py#L58-L60

So why do virtual methods get ignored by the obfuscator? Because they can be overridden. Take your example: `onCreate`, `onResume` and `onPause` are virtual too, so if virtual methods weren't ignored, those methods would be renamed as well (and this would definitely break the app). There is no easy way to determine if a method is overriding or is being overridden, that's why currently virtual methods are skipped.

**Comment by tracer8** [comment]
I got it, now i will modify my code to reduce virtual methods as much as
possible.
Thank you so much!
