### ISSUE TITLE
Can't use print method to show debug log.

### ISSUE THREAD

**Issue by tracer8** [ClaudiuGeorgiu/Obfuscapk#44]
Hi,
I have modify some part of code, and i try to add some print to debug somethings, but it did't show anything. Did you add any code to prevent show print log to console?

Example:
- On class_rename.py
- I try to add print method to this:
```
 def encrypt_identifier(self, identifier: str) -> str:
        identifier_md5 = util.get_string_md5(identifier)
        result = 'p{0}'.format(identifier_md5.lower()[:16])
        print("Class name: " + result)
        return result
```
- But it did't show anything on console.

**Comment by packmad** [comment]
I don't know why `print` isn't working, but use `logging`
Every class has ` self.logger`

**Comment by ClaudiuGeorgiu** [comment]
> Did you add any code to prevent show print log to console?

Hi, before commit c9e493b6b6656f58a46108101432064b93874056 `print` statements would write to the smali file being modified instead of the console. However, in the latest version you can use the code you wrote above, so if it's not working please download the latest version of Obfuscapk.

> use `logging`
> Every class has ` self.logger`

This is the preferred solution, use `self.logger.info("Class name: " + result)`.
