### ISSUE TITLE
Sugestion. obfuscatedAPK is not being accept in Google Play Store

### ISSUE THREAD

**Issue by excellentiam-prog** [ClaudiuGeorgiu/Obfuscapk#63]
First of all, I would like to thank you for obfuscapk.

I created the obfuscated apk, the level of obfuscation is impressive. Unfortunately, I tried to upload the apk on Play Store and it was refused because "Error from apksigner: ERROR: MIN_SIG_SCHEME_FOR_TARGET_SDK_NOT_MET", attached,
![playstore](https://user-images.githubusercontent.com/66888451/99137587-a84bcb00-260a-11eb-8538-da9fec675cad.png)
 and I use the same keystore for all my apps and apksigner is in the environment path.

I believe that would be great if obfuscapk could work on the JAVA files and android manifest before we build the apk or bundle, and Android Studio finishes it. 

We select the folder "com.myapp", android manifest.xml, res folder, native folder... using a simple GUI made with PyQt. Then, we put the generated folders and android manifest back, Android Studio ends. I believe that this way would work for very long time, regardless of the new requirements, because Android Studio would meet them. Probably, .apk will be replaced by bundle .aab quickly.

**Comment by ClaudiuGeorgiu** [comment]
Hi, the signature error should be fixable by using `apksigner` instead of `jarsigner` (which uses only the v1 signature scheme), thanks for reporting, we will add this feature in a future release. As a temporary solution, you could omit `NewSignature` obfuscator and sign the apk manually. However, please note that we haven't tested the upload on the Play Store of apps obfuscated with Obfuscapk, so there is no guarantee that everything will work as expected even if you manage to solve the signature issue.

> I believe that would be great if obfuscapk could work on the JAVA files and android manifest before we build the apk or bundle, and Android Studio finishes it.

Thanks for the suggestion but I don't think this will happen (or at least not soon), since the idea behind Obfuscapk is to make a completely black box tool that doesn't need the source code of the application.

**Comment by excellentiam-prog** [comment]
> Hi, the signature error should be fixable by using `apksigner` instead of `jarsigner` (which uses only the v1 signature scheme), thanks for reporting, we will add this feature in a future release. As a temporary solution, you could omit `NewSignature` obfuscator and sign the apk manually. However, please note that we haven't tested the upload on the Play Store of apps obfuscated with Obfuscapk, so there is no guarantee that everything will work as expected even if you manage to solve the signature issue.
> 
> > I believe that would be great if obfuscapk could work on the JAVA files and android manifest before we build the apk or bundle, and Android Studio finishes it.
> 
> Thanks for the suggestion but I don't think this will happen (or at least not soon), since the idea behind Obfuscapk is to make a completely black box tool that doesn't need the source code of the application.

Thank you, I will try the apksigner. About the apk: "Important: In the second half of 2021, new apps will be required to publish with the Android App Bundle on Google Play. New apps larger than 150 MB must use either Play Feature Delivery or Play Asset Delivery." https://developer.android.com/guide/app-bundle
